### ISSUE TITLE
dateTimePicker not worked!

### ISSUE THREAD

**Issue by Sinersis** [icebob/vue-form-generator#111]
Error text `"Bootstrap datetimepicker library is missing. Please download from https://eonasdan.github.io/bootstrap-datetimepicker/ and load the script and CSS in the HTML head section!"`
What can I do to work?
Vue 2.0

**Comment by cristijora** [comment]
The errors seems pretty straightforward. Add a script tag with the bootstrap datepicker.
https://eonasdan.github.io/bootstrap-datetimepicker/Installing/#manual
Since this plugin is dependent on jquery and the plugin itself it checks if the jquery and datetimepicker are in the window object 
`if(window.$ && window.$.fn.datetimepicker)` 
Just make sure you have the plugin initialized according to it's docs. As long as you pass over that part it should work fine.

**Comment by icebob** [comment]
@cristijora thanks for your help.

**Comment by Sinersis** [comment]
Hm... Where i can add dependency? I use vue with laravel 5.4... but i understand your idea

**Comment by Sinersis** [comment]
problem number two now. Now, do not change the model to join a variety of dates. What could be the problem?

**Comment by icebob** [comment]
Please show your schema and version number of vue-form-generator.

**Comment by Sinersis** [comment]
`{
                        type: "dateTimePicker",
                        label: "Start",
                        model: "Start",
                        required: true,
                        placeholder: "Start date",
                        pikadayOptions: {
                            format: "YYYY-MM-DD"
                        }
                    },
                    {
                        type: "dateTimePicker",
                        label: "ExpirationTime",
                        model: "ExpirationTime",
                        required: true,
                        placeholder: "Expiration date",
                        pikadayOptions: {
                            format: "YYYY-MM-DD"
                        }
                    },`
"vue-form-generator": "^2.0.0-beta3",

**Comment by cristijora** [comment]
See working [fiddle](https://jsfiddle.net/0mg1v81e/148/). This field depends on moment, bootstrap and the plugin itself (see external resources on the left)

**Comment by icebob** [comment]
@Sinersis there was a refresh error in date fields (#118). They are fixed. Tomorrow I will make a new beta release with them.

**Comment by icebob** [comment]
Please test with beta4 release

**Comment by bhupender005** [comment]
Hello guys, I am trying to achieve this using main.js but getting above error

main.js
import Vue from 'vue'
import App from './App'
import Header from './Header'
import router from './router'
import VueFormGenerator from 'vue-form-generator'
import Bootstrap from 'bootstrap'
import BootstrapDatePicker from 'bootstrap-datepicker'
import Moment from 'moment'

import 'bootstrap/dist/css/bootstrap.css'
import 'vue-form-generator/dist/vfg.css'

import 'bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js'
import 'bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css'

Vue.config.productionTip = false
Vue.component('app-header', Header)
Vue.use({Bootstrap, VueFormGenerator, Moment, BootstrapDatePicker})
Vue.component('vue-form-generator', VueFormGenerator.component)

/* eslint-disable no-new */
new Vue({
  el: '#app',
  router,
  template: '<App/>',
  components: { App }
})

**Comment by cristijora** [comment]
Shouldn't BootstrapDatePicker be registered firt in your case before FormGenerator?
`Vue.use({Bootstrap, Moment, BootstrapDatePicker, VueFormGenerator})`

**Comment by bhupender005** [comment]
@cristijora Still getting same error
"Bootstrap datetimepicker library is missing. Please download from https://eonasdan.github.io/bootstrap-datetimepicker/ and load the script and CSS in the HTML head section!"

**Comment by icebob** [comment]
@bhupender005 I don't think you can use these non-vue modules with `Vue.use`. Check the dev example in `dev` folder how we can use them.

**Comment by cristijora** [comment]
@icebob Says right. Indeed those modules are not Vue plugins so you can't use them like that. Only FormGenerator is. So dumb for not seing that 🦆

**Comment by bhupender005** [comment]
@icebob Thanks for info
@cristijora I am too new to VueJS, my bad

Guys couldn't find dev folder, can you help me how to use "datepicker". Can you help me how to include these plugins/files in my current scenario (VueJS web-package)

**Comment by lionel-bijaoui** [comment]
@bhupender005 Sorry, but this is out of the scope of this plugin and the use of the issue tracker.
If you want to find help you can ask any question you like on the [official Vuejs Forum](https://forum.vuejs.org/) or the [Vuejs Gitter channel](https://gitter.im/vuejs/vue).
Of course, if you have an issue or question directly related to this plugin and it's use feel free to [open another issue](https://github.com/icebob/vue-form-generator/issues/new).
Good luck !

**Comment by timoteo7** [comment]
for Vue.js install:
`npm install vue-bootstrap-datetimepicker`

and import:
```
import datePicker from 'vue-bootstrap-datetimepicker';
import 'pc-bootstrap4-datetimepicker/build/css/bootstrap-datetimepicker.css';
```

**Comment by MB175** [comment]
@timoteo7  where did you place the Imports. I have tried alot so far and cant get anything  to work.
Still stuck at.
`Bootstrap datetimepicker library is missing. Please download`
